# Generated by Django 6.0.3 on 2026-04-05 06:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="inviter_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="invitation",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
