# Generated by Django 6.0.3 on 2026-04-05 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_invitation_inviter_email_invitation_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
