# Generated by Django 6.0.3 on 2026-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="logdefinition",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
