# Generated by Django 6.0.3 on 2026-04-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_logentry_timestamp_alter_logdefinition_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logentry",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="logentry",
            name="is_archived",
        ),
        migrations.AlterField(
            model_name="logentry",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
