# Generated by Django 6.0.3 on 2026-04-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_remove_logentry_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
