# Generated by Django 6.0.3 on 2026-04-10 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0004_logentry_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="logdefinition",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="logdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("name",),
                name="unique_active_name",
            ),
        ),
    ]
